### PR TITLE
Tweak README

### PR DESCRIPTION
**Pull request by ml-evs**
I think this looks marginally cleaner

### CODE REVIEW

**Review by ppdebreuck — APPROVED** [review]
Agreed.

**Comment by ml-evs** [comment]
Here's the root cause of the test failures, have asked for it to be fixed upstream: https://github.com/materialsproject/api/issues/819

**Comment by ppdebreuck** [comment]
emmet-core pinning seems not to help ? Any idea ?

**Comment by ml-evs** [comment]
Indeed, now things are broken because pydantic 2.0 has been released and no-one was pinning to v1...

**Pull request merged**
